name: Build docker image
on:
  workflow_dispatch:
env:
  IMAGE: ghcr.io/${{ github.repository }}/formio-enterprise-nav:7.3.2


jobs:

  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v2"
      - name: "Build and push Docker image"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          docker build --tag ${IMAGE} .
          echo ${GITHUB_TOKEN} | docker login ghcr.io -u ${{ github.repository }} --password-stdin
          docker push ${IMAGE}
