name: Build docker image
on:
  workflow_dispatch:
env:
  IMAGE: "ghcr.io/navikt/formio-enterprise-deployment/formio-enterprise-nav:7.3.2"


jobs:

  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v2"
      - name: "Build and push Docker image"
        run: |
          docker build --tag ${IMAGE} .
          echo ${{ secrets.GITHUB_TOKEN }} | docker login -u ${{ github.repository }} --password-stdin https://docker.pkg.github.com
          docker push ${IMAGE}
